# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Todos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Alamofire',  '~> 4.4'
  # Pods for Todos

end
